### ISSUE TITLE
Anystyle Parsing not working

### ISSUE THREAD

**Issue by ghost** [inukshuk/anystyle-cli#18]
Hi.

I installed a completely fresh and new version of Ruby as well as Anystyle.
Also, I did not install other Gems than Anystyle.

Anystyle is not working when parsing.

Please advise.

Best regards
Frank Nielsen
frank230458@yahoo.dk

**************************************************

C:\Ruby32-x64>anystyle --version
anystyle version 1.4.0 (cli 1.4.2, data 1.3.0)

C:\Ruby32-x64>anystyle check Five.txt
Checking Five.txt.................error: undefined method `[]' for #<ArgumentError: cannot check untagged input: C:/Ruby32-x64/Five.txt>

C:\Ruby32-x64>anystyle parse Five.txt
Error processing `Five.txt'
  undefined local variable or method `input' for #<AnyStyle::CLI::Commands::Parse:0x000001f1221e4938 @options={"F"=>nil, :F=>nil, "finder-model"=>nil, :"finder-model"=>nil, "P"=>nil, :P=>nil, "parser-model"=>nil, :"parser-model"=>nil, "pdftotext"=>nil, :pdftotext=>nil, "pdfinfo"=>nil, :pdfinfo=>nil, "adapter"=>"ruby", :adapter=>"ruby", "f"=>["json"], :f=>["json"], "format"=>["json"], :format=>["json"], "version"=>false, :version=>false, "verbose"=>false, :verbose=>false, "w"=>false, :w=>false, "overwrite"=>false, :overwrite=>false, "stdout"=>false, :stdout=>true, "help"=>false, :help=>false}>
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/anystyle-cli-1.4.2/lib/anystyle/cli/commands/base.rb:39:in `parse_file'
  C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/anystyle-cli-1.4.2/lib/anystyle/cli/commands/parse.rb:9:in `block in run'
  ...

C:\Ruby32-x64>

[Five.pdf](https://github.com/inukshuk/anystyle-cli/files/10508422/Five.pdf)
[Five.txt](https://github.com/inukshuk/anystyle-cli/files/10508429/Five.txt)

**Comment by inukshuk** [comment]
Hi, please install version 1.4.4 of the `anystyle-cli` Gem (above it is 1.4.2). This version was pushed earlier today so your local cache may not have been re-freshed yet. If it's still not fetching the latest version you can try with `gem install anystyle-cli --version 1.4.4`.

**Comment by inukshuk** [comment]
Oh, the `check` and `train` commands were also affected by the previous bug. They are fixed in 1.4.5 (pushed just now). However, if you use the `check` command you need to use a tagged XML file for the parser. An untagged input file can't be checked of course.

**Comment by ghost** [comment]
Dear Sylvester.

There are several reference types and exceptions. I know it is very complicated.

You did some fantastic work making this Anystyle gem.


Sent from Yahoo Mail on Android 
 
  On Thu, 26 Jan 2023 at 12:03, Sylvester ***@***.***> wrote:   


Oh, the check and train commands were also affected by the previous bug. They are fixed in 1.4.5 (pushed just now). However, if you use the check command you need to use a tagged XML file for the parser. An untagged input file can't be checked of course.
